import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  FormOutline,
  DashboardOutline,
  SettingOutline,
  PieChartOutline,
  ApartmentOutline,
  CreditCardOutline,
  QuestionCircleOutline,
  DollarOutline,
  EyeOutline,
  EyeInvisibleOutline,
  MailOutline,
  ArrowLeftOutline,
  DeleteFill,
  DeleteOutline,
  PlusSquareFill,
  PlusOutline,
  DiffOutline,
} from '@ant-design/icons-angular/icons';

export const icons = [
  MenuFoldOutline,
  MenuUnfoldOutline,
  DashboardOutline,
  FormOutline,
  SettingOutline,
  PieChartOutline,
  ApartmentOutline,
  CreditCardOutline,
  QuestionCircleOutline,
  DollarOutline,
  EyeOutline,
  EyeInvisibleOutline,
  MailOutline,
  ArrowLeftOutline,
  DeleteFill,
  DeleteOutline,
  PlusOutline,
  PlusSquareFill,
  DiffOutline
];